title: Your awesome title
author: DanielC
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My awesome webpage for the Github page tutorial.

theme: minima

# social links
twitter_username: No-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  dnlchng # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
